### ISSUE TITLE
V1.0.0 todo list

### ISSUE THREAD

**Issue by mrjvs** [movie-web/backend#1]
# backend
- [ ] Account system
  - [ ] Account creation
  - [ ] register device (create token)
  - [ ] unregistering device (expire token)
  - [ ] login (passwordless)
  - [ ] recaptcha support (for register and login)
- [ ] Prometheus support
  - [ ] whats being watched metrics
  - [ ] successfull scrape metrics
  - [ ] user count metrics
- [ ] meta endpoint (node hostname, backend version)
- [ ] data saving
  - [ ] settings
  - [ ] bookmarks
  - [ ] watch progress
  - [ ] sensible limits, so we don't get used as a free database
  - [ ] import legacy data
  
# Client implementation
- [ ] offline first syncing
- [ ] supported version checking (on load: load meta data, check if client supports the backend version)
